name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.11
        with:
          
          heroku_app_name: "pharaohapp"
          heroku_email: "liamandell14@gmail.com"
          heroku_api_key: ${{secrets.0b3f2fb2-9bba-461d-b886-0d08c9261cfe}}